[colors]

# Primary colors
[colors.primary]
background = "0xd1cdb7"
foreground = "0x454138"

# Cursor colors
[colors.cursor]
text = "0xd1cdb7"
cursor = "0x454138"

# Selection colors
[colors.selection]
text = "0xdcd8c0"
background = "0x454138"

# Normal colors (color0–color7)
[colors.normal]
black   = "0xd1cdb7" # color0
red     = "0x8b2020" # color1
green   = "0x5a5248" # color2
yellow  = "0x7a6a3a" # color3
blue    = "0x454138" # color4
magenta = "0x5a5248" # color5
cyan    = "0x6a6358" # color6
white   = "0x454138" # color7

# Bright colors (color8–color15)
[colors.bright]
black   = "0xbab5a1" # color8
red     = "0x8b2020" # color9
green   = "0x5a5248" # color10
yellow  = "0x7a6a3a" # color11
blue    = "0x454138" # color12
magenta = "0x5a5248" # color13
cyan    = "0x6a6358" # color14
white   = "0x1a1814" # color15
