# Background and Foreground
background = #d1cdb7
foreground = #454138

# Cursor
cursor-color = #454138
cursor-text  = #dcd8c0

# Selection
selection-background = #454138
selection-foreground = #dcd8c0

# Color Palette (YoRHa Light)
palette = 0=#d1cdb7
palette = 1=#8b2020
palette = 2=#454138
palette = 3=#7a6a3a
palette = 4=#454138
palette = 5=#5a5248
palette = 6=#6a6358
palette = 7=#454138
palette = 8=#bab5a1
palette = 9=#8b2020
palette = 10=#5a5248
palette = 11=#7a6a3a
palette = 12=#454138
palette = 13=#5a5248
palette = 14=#6a6358
palette = 15=#1a1814
